// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

package century.net.test.msg;

public interface TestSignatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:century.net.test.msg.TestSignature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.century.net.test.msg.TestEnum errcode = 1;</code>
   */
  int getErrcodeValue();
  /**
   * <code>.century.net.test.msg.TestEnum errcode = 1;</code>
   */
  century.net.test.msg.TestEnum getErrcode();

  /**
   * <code>int64 timestamp = 2;</code>
   */
  long getTimestamp();

  /**
   * <code>int64 timecount = 3;</code>
   */
  long getTimecount();

  /**
   * <code>string sign = 4;</code>
   */
  java.lang.String getSign();
  /**
   * <code>string sign = 4;</code>
   */
  com.google.protobuf.ByteString
      getSignBytes();
}
