// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

package century.net.test.msg;

public final class TestMessage {
  private TestMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_century_net_test_msg_TestString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_century_net_test_msg_TestString_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_century_net_test_msg_TestSignature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_century_net_test_msg_TestSignature_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncore.proto\022\024century.net.test.msg\"\035\n\nTe" +
      "stString\022\017\n\007lineKey\030\001 \001(\t\"t\n\rTestSignatu" +
      "re\022/\n\007errcode\030\001 \001(\0162\036.century.net.test.m" +
      "sg.TestEnum\022\021\n\ttimestamp\030\002 \001(\003\022\021\n\ttimeco" +
      "unt\030\003 \001(\003\022\014\n\004sign\030\004 \001(\t*M\n\010TestEnum\022\013\n\007S" +
      "UCCESS\020\000\022\r\n\tTO_SYSCTL\020\001\022\021\n\rTO_DISCONNECT" +
      "\020\002\022\022\n\016RR_NO_TIMELINE\020\003B%\n\024century.net.te" +
      "st.msgB\013TestMessageP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_century_net_test_msg_TestString_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_century_net_test_msg_TestString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_century_net_test_msg_TestString_descriptor,
        new java.lang.String[] { "LineKey", });
    internal_static_century_net_test_msg_TestSignature_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_century_net_test_msg_TestSignature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_century_net_test_msg_TestSignature_descriptor,
        new java.lang.String[] { "Errcode", "Timestamp", "Timecount", "Sign", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
