// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

package century.net.test.msg;

/**
 * Protobuf type {@code century.net.test.msg.TestSignature}
 */
public  final class TestSignature extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:century.net.test.msg.TestSignature)
    TestSignatureOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TestSignature.newBuilder() to construct.
  private TestSignature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TestSignature() {
    errcode_ = 0;
    sign_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TestSignature();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TestSignature(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            errcode_ = rawValue;
            break;
          }
          case 16: {

            timestamp_ = input.readInt64();
            break;
          }
          case 24: {

            timecount_ = input.readInt64();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            sign_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return century.net.test.msg.TestMessage.internal_static_century_net_test_msg_TestSignature_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return century.net.test.msg.TestMessage.internal_static_century_net_test_msg_TestSignature_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            century.net.test.msg.TestSignature.class, century.net.test.msg.TestSignature.Builder.class);
  }

  public static final int ERRCODE_FIELD_NUMBER = 1;
  private int errcode_;
  /**
   * <code>.century.net.test.msg.TestEnum errcode = 1;</code>
   */
  public int getErrcodeValue() {
    return errcode_;
  }
  /**
   * <code>.century.net.test.msg.TestEnum errcode = 1;</code>
   */
  public century.net.test.msg.TestEnum getErrcode() {
    @SuppressWarnings("deprecation")
    century.net.test.msg.TestEnum result = century.net.test.msg.TestEnum.valueOf(errcode_);
    return result == null ? century.net.test.msg.TestEnum.UNRECOGNIZED : result;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 2;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int TIMECOUNT_FIELD_NUMBER = 3;
  private long timecount_;
  /**
   * <code>int64 timecount = 3;</code>
   */
  public long getTimecount() {
    return timecount_;
  }

  public static final int SIGN_FIELD_NUMBER = 4;
  private volatile java.lang.Object sign_;
  /**
   * <code>string sign = 4;</code>
   */
  public java.lang.String getSign() {
    java.lang.Object ref = sign_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sign_ = s;
      return s;
    }
  }
  /**
   * <code>string sign = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSignBytes() {
    java.lang.Object ref = sign_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sign_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (errcode_ != century.net.test.msg.TestEnum.SUCCESS.getNumber()) {
      output.writeEnum(1, errcode_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(2, timestamp_);
    }
    if (timecount_ != 0L) {
      output.writeInt64(3, timecount_);
    }
    if (!getSignBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sign_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (errcode_ != century.net.test.msg.TestEnum.SUCCESS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, errcode_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timestamp_);
    }
    if (timecount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, timecount_);
    }
    if (!getSignBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sign_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof century.net.test.msg.TestSignature)) {
      return super.equals(obj);
    }
    century.net.test.msg.TestSignature other = (century.net.test.msg.TestSignature) obj;

    if (errcode_ != other.errcode_) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (getTimecount()
        != other.getTimecount()) return false;
    if (!getSign()
        .equals(other.getSign())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
    hash = (53 * hash) + errcode_;
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + TIMECOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimecount());
    hash = (37 * hash) + SIGN_FIELD_NUMBER;
    hash = (53 * hash) + getSign().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static century.net.test.msg.TestSignature parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static century.net.test.msg.TestSignature parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static century.net.test.msg.TestSignature parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static century.net.test.msg.TestSignature parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static century.net.test.msg.TestSignature parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static century.net.test.msg.TestSignature parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static century.net.test.msg.TestSignature parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static century.net.test.msg.TestSignature parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static century.net.test.msg.TestSignature parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static century.net.test.msg.TestSignature parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static century.net.test.msg.TestSignature parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static century.net.test.msg.TestSignature parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(century.net.test.msg.TestSignature prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code century.net.test.msg.TestSignature}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:century.net.test.msg.TestSignature)
      century.net.test.msg.TestSignatureOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return century.net.test.msg.TestMessage.internal_static_century_net_test_msg_TestSignature_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return century.net.test.msg.TestMessage.internal_static_century_net_test_msg_TestSignature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              century.net.test.msg.TestSignature.class, century.net.test.msg.TestSignature.Builder.class);
    }

    // Construct using century.net.test.msg.TestSignature.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      errcode_ = 0;

      timestamp_ = 0L;

      timecount_ = 0L;

      sign_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return century.net.test.msg.TestMessage.internal_static_century_net_test_msg_TestSignature_descriptor;
    }

    @java.lang.Override
    public century.net.test.msg.TestSignature getDefaultInstanceForType() {
      return century.net.test.msg.TestSignature.getDefaultInstance();
    }

    @java.lang.Override
    public century.net.test.msg.TestSignature build() {
      century.net.test.msg.TestSignature result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public century.net.test.msg.TestSignature buildPartial() {
      century.net.test.msg.TestSignature result = new century.net.test.msg.TestSignature(this);
      result.errcode_ = errcode_;
      result.timestamp_ = timestamp_;
      result.timecount_ = timecount_;
      result.sign_ = sign_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof century.net.test.msg.TestSignature) {
        return mergeFrom((century.net.test.msg.TestSignature)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(century.net.test.msg.TestSignature other) {
      if (other == century.net.test.msg.TestSignature.getDefaultInstance()) return this;
      if (other.errcode_ != 0) {
        setErrcodeValue(other.getErrcodeValue());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getTimecount() != 0L) {
        setTimecount(other.getTimecount());
      }
      if (!other.getSign().isEmpty()) {
        sign_ = other.sign_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      century.net.test.msg.TestSignature parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (century.net.test.msg.TestSignature) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int errcode_ = 0;
    /**
     * <code>.century.net.test.msg.TestEnum errcode = 1;</code>
     */
    public int getErrcodeValue() {
      return errcode_;
    }
    /**
     * <code>.century.net.test.msg.TestEnum errcode = 1;</code>
     */
    public Builder setErrcodeValue(int value) {
      errcode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.century.net.test.msg.TestEnum errcode = 1;</code>
     */
    public century.net.test.msg.TestEnum getErrcode() {
      @SuppressWarnings("deprecation")
      century.net.test.msg.TestEnum result = century.net.test.msg.TestEnum.valueOf(errcode_);
      return result == null ? century.net.test.msg.TestEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.century.net.test.msg.TestEnum errcode = 1;</code>
     */
    public Builder setErrcode(century.net.test.msg.TestEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      errcode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.century.net.test.msg.TestEnum errcode = 1;</code>
     */
    public Builder clearErrcode() {
      
      errcode_ = 0;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 2;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 2;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private long timecount_ ;
    /**
     * <code>int64 timecount = 3;</code>
     */
    public long getTimecount() {
      return timecount_;
    }
    /**
     * <code>int64 timecount = 3;</code>
     */
    public Builder setTimecount(long value) {
      
      timecount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timecount = 3;</code>
     */
    public Builder clearTimecount() {
      
      timecount_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object sign_ = "";
    /**
     * <code>string sign = 4;</code>
     */
    public java.lang.String getSign() {
      java.lang.Object ref = sign_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sign_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sign = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      java.lang.Object ref = sign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sign = 4;</code>
     */
    public Builder setSign(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sign_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sign = 4;</code>
     */
    public Builder clearSign() {
      
      sign_ = getDefaultInstance().getSign();
      onChanged();
      return this;
    }
    /**
     * <code>string sign = 4;</code>
     */
    public Builder setSignBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sign_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:century.net.test.msg.TestSignature)
  }

  // @@protoc_insertion_point(class_scope:century.net.test.msg.TestSignature)
  private static final century.net.test.msg.TestSignature DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new century.net.test.msg.TestSignature();
  }

  public static century.net.test.msg.TestSignature getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TestSignature>
      PARSER = new com.google.protobuf.AbstractParser<TestSignature>() {
    @java.lang.Override
    public TestSignature parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TestSignature(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TestSignature> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TestSignature> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public century.net.test.msg.TestSignature getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

