// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

package century.net.test.msg;

public interface TestStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:century.net.test.msg.TestString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lineKey = 1;</code>
   */
  java.lang.String getLineKey();
  /**
   * <code>string lineKey = 1;</code>
   */
  com.google.protobuf.ByteString
      getLineKeyBytes();
}
